### ISSUE TITLE
calculation of AIC

### ISSUE THREAD

**Issue by NcyFS** [jknape/poptrend#1]
Hi, 

I was wondering if there were a way to calculate AIC with poptend ? When I try AIC(model$gam), I get an NA value.
Thanks so much for all your help,

Nancy

**Comment by jknape** [comment]
Hi Nancy,

By (current) default ptrend uses a quasipoisson family, and mgcv does not compute AIC for quasi-distributions (i.e. qAIC). My first suggestion would be to try a negative binomial distribution instead (e.g. family = 'nb').

Jonas

**Comment by NcyFS** [comment]
Hi Jonas, 

I thank you so much for your response, I was not aware the default was quasi-poisson, now I understand.

Nancy

**Comment by NcyFS** [comment]
I thank you so much, It is exactly what I needed ! Thank you again !
