### ISSUE TITLE
systematic increase of standard deviation since the first year

### ISSUE THREAD

**Issue by NcyFS** [jknape/poptrend#3]
Hi, on the graphs I made, I observe systematically an increase of the standard deviation since the first year. Is this normal? I may have missed something in the paper in relation to the first year beeing used as a reference. Thank you in advance for all your help,
 
Nancy
![Image1](https://user-images.githubusercontent.com/80974983/145856528-cce283d4-5a75-4886-a9b4-6dad87bb46cd.png)

**Comment by jknape** [comment]
Hi Nancy,
Yes, this is expected. The default is that the trend line in the first year is used as a reference, meaning that indices in all years are compared relative to the trend line in the first year. Because of this there is no uncertainty in the smoothed index for the first year.
Jonas

**Comment by NcyFS** [comment]
Hi Jonas, 
Thanks so much for your answer ! Have a very good day and nice holidays, 
Nancy
