### ISSUE TITLE
Creating figure without colors along the x axis.

### ISSUE THREAD

**Issue by mpward55** [jknape/poptrend#4]
How can I produce the population trend figures without the colors along the x axis?

Thanks
Mike

**Comment by jknape** [comment]
This isn't possible from the CRAN version right now, but if you install from github using e.g.
```
library(devtools)
install_github('jknape/poptrend')
```
there is an option 'secDeriv' to the plot function. If you set that to FALSE the boxes along the x-axis will be removed.

**Comment by mpward55** [comment]
Thanks!
