### ISSUE TITLE
Figure options

### ISSUE THREAD

**Issue by PatWright** [jknape/poptrend#5]
Hello,
I've been asked by a reviewer to remove the annual random effect points and the vertical lines as it would my figures a bit clearer. I think that in this context it's a good idea as I have multiple plots at the same scale for comparison and some of these do end up not being very clear as a result. Is it possible to remove them?
Thanks.

My plots:
a<-plot(trendFXGHB, ylim = c(0,1.6), ciBase = 2009,shadeCol=adjustcolor("gray", alpha.f = 0.4), xlab = "year", main = "GHB - Britain")

**Comment by jknape** [comment]
This does seem useful to have. There's no neat way of doing this in the cran package, but I have added an option 'ranef' to the git version. If you set it to 'no', random effects should be removed. To install the github version, use library(devtools); install_github("jknape/poptrend").

In the cran version, you could try the hack of setting trendFXGHB$timeRE = FALSE before plotting (and reset it to TRUE afterwards if you plan on using the object for something else).

**Comment by PatWright** [comment]
Thanks! The cran version hack worked well.
